# Generated by Django 5.0.7 on 2024-08-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Linkedprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='logo',
        ),
    ]
