# Generated by Django 5.0.7 on 2024-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkedprofile', '0002_rename_banner_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='mains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='product/banner')),
            ],
        ),
    ]
